/* Generates the token's Solidity source from the switches.
 *
 * Deliberately flat: one file, no imports, no inheritance from a library the
 * launcher cannot see. Two reasons, and both matter more than elegance here.
 *
 *   1. The person deploying can read the whole thing. A contract that says
 *      `is ERC20, Ownable, Pausable` hides exactly the powers this page exists
 *      to make visible.
 *   2. Compiling in the browser stays simple — no import resolution, no
 *      network fetch for OpenZeppelin at compile time, so it works offline and
 *      cannot silently pull a different version than the one displayed.
 *
 * Nothing here refuses to build. Every warning this file produces is text, not
 * a gate: the source is shown, editable and copyable, so anyone who disagrees
 * with the advice can ignore it, edit it, or skip the page entirely and deploy
 * the same bytecode themselves. That is the point.
 */

const SPDX = "// SPDX-License-Identifier: MIT";
const PRAGMA = "pragma solidity ^0.8.24;";

function esc(s) {
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/* The schema is not invented here. It is the one this chain's indexers already
 * parse: image, website, twitter, telegram, description. Our own indexer reads
 * exactly those five keys (blop-indexer/src/discovery.js), which is why a token
 * launched with them shows its picture without anyone being asked to add it. */
function metadataJSON(state) {
  const pairs = [];
  const put = (k, v) => { if (v && String(v).trim()) pairs.push('"' + k + '":"' + esc(String(v).trim()) + '"'); };
  put("name", state.name);
  put("symbol", state.symbol);
  put("description", state.metaDescription);
  put("image", state.metaImage);
  put("website", state.metaWebsite);
  put("twitter", state.metaTwitter);
  put("telegram", state.metaTelegram);
  return "{" + pairs.join(",") + "}";
}

export function metadataPreview(state) {
  if (state.metaMode === "none") return null;
  return state.metaMode === "uri" ? (state.metaUri || "") : metadataJSON(state);
}

function ident(symbol) {
  const c = String(symbol || "Token").replace(/[^A-Za-z0-9]/g, "");
  const s = c.length ? c : "Token";
  return /^[0-9]/.test(s) ? "T" + s : s;
}

export function generateSource(state) {
  const S = state;
  const name = ident(S.symbol);
  const up = !!S.upgradeable;
  const owned =
    S.mintable || S.pausable || S.blacklist || S.tradingToggle || S.maxTx || S.transferTax ||
    /* An editable metadata URI is an owner-only function like any other, so it
     * drags in the owner machinery even when nothing else did. */
    (S.metaMutable && S.metaMode && S.metaMode !== "none");

  const L = [];
  const p = (line) => L.push(line === undefined ? "" : line);

  p(SPDX);
  p(PRAGMA);
  p();
  p("/*");
  p(" * " + S.name + " (" + S.symbol + ")");
  p(" *");
  p(" * Generated by the Arc launcher. Every switch that is on appears below as");
  p(" * real code — if a power is not in this file, nobody has it.");
  if (up) {
    p(" *");
    p(" * THIS IS THE IMPLEMENTATION BEHIND A PROXY. Read that sentence twice:");
    p(" * everything below describes the code running TODAY. The proxy admin can");
    p(" * point at different code tomorrow, including code with a mint function,");
    p(" * a blacklist, or no transfer function at all. Nothing in this file is a");
    p(" * promise about the future — only about the present.");
  } else {
    p(" *");
    p(" * Fixed at deploy and never changeable: name, symbol, decimals" + (S.mintable ? "" : ", total supply") + ".");
  }
  if (owned) {
    p(" *");
    p(" * OWNER POWERS IN THIS CONTRACT:");
    if (S.mintable) p(" *   - mint(): create new tokens at will" + (S.capped ? ", up to the hard cap" : ", with no limit"));
    if (S.pausable) p(" *   - pause(): freeze every transfer, for everyone");
    if (S.blacklist) p(" *   - setBlocked(): stop a specific address sending or receiving");
    if (S.tradingToggle) p(" *   - enableTrading(): one-way switch, trading is OFF until called");
    if (S.maxTx) p(" *   - setLimits(): change the per-transfer and per-wallet caps");
    if (S.transferTax) p(" *   - setTax(): change the transfer fee, up to the hard ceiling below");
    if (S.metaMutable && S.metaMode && S.metaMode !== "none") {
      p(" *   - setMetadataURI(): change the picture, the description and the links");
    }
    p(" *");
    p(
      S.ownership === "renounce"
        ? " * Ownership is renounced at initialisation, so none of the above can ever"
        : " * Ownership is retained by the deployer, so all of the above can"
    );
    p(S.ownership === "renounce" ? " * be called. Verify: owner() returns the zero address." : " * be called at any time. Verify: owner() returns the deployer.");
  } else {
    p(" *");
    p(" * There are no owner-only functions in this contract at all.");
  }
  p(" */");
  p();
  p("contract " + name + " {");
  p("    string public constant name = \"" + esc(S.name) + "\";");
  p("    string public constant symbol = \"" + esc(S.symbol) + "\";");
  p("    uint8 public constant decimals = " + S.decimals + ";");
  p();
  p("    uint256 public totalSupply;");
  p("    mapping(address => uint256) public balanceOf;");
  p("    mapping(address => mapping(address => uint256)) public allowance;");
  p();
  p("    event Transfer(address indexed from, address indexed to, uint256 value);");
  p("    event Approval(address indexed owner, address indexed spender, uint256 value);");

  if (S.metaMode && S.metaMode !== "none") {
    const inline = S.metaMode === "inline";
    const valor = inline ? metadataJSON(S) : String(S.metaUri || "").trim();
    p();
    p("    /// Picture, description and links. metadataURI() is what indexers on");
    p("    /// this chain already read \u2014 both this launcher's own platform token");
    p("    /// and other launchpads here expose exactly this getter.");
    if (inline) {
      p("    /// The JSON lives IN the contract: no gateway, no host, nothing to keep");
      p("    /// alive. It costs more gas once and then cannot rot.");
    } else {
      p("    /// This is a link. Whoever serves it decides whether it keeps working \u2014");
      p("    /// an IPFS pin that lapses or a domain that expires takes the picture");
      p("    /// with it, and the contract will keep pointing at nothing.");
    }
    if (S.metaMutable) {
      p("    string public metadataURI;");
    } else {
      p("    /// Fixed at deploy. Nobody can change it later, including you \u2014 which");
      p("    /// also means a wrong link is wrong forever.");
      p("    string public constant metadataURI = \"" + esc(valor) + "\";");
    }
  }

  if (S.capped && S.mintable) {
    p();
    if (up) {
      p("    /// Hard ceiling on total supply. NOT immutable here, because an");
      p("    /// immutable lives in the implementation's code and a proxy upgrade");
      p("    /// would replace it. Behind a proxy, a cap is a promise, not a law.");
      p("    uint256 public maxSupply;");
    } else {
      p("    /// Hard ceiling on total supply. Immutable: not even the owner can raise it.");
      p("    uint256 public immutable maxSupply;");
    }
  }

  if (up) {
    p();
    p("    bool private _initialized;");
  }

  if (owned) {
    p();
    p("    address public owner;");
    p("    event OwnershipTransferred(address indexed from, address indexed to);");
    p();
    p("    modifier onlyOwner() {");
    p("        require(msg.sender == owner, \"not the owner\");");
    p("        _;");
    p("    }");
  }

  if (S.pausable) {
    p();
    p("    bool public paused;");
    p("    event Paused(bool state);");
  }
  if (S.blacklist) {
    p();
    p("    mapping(address => bool) public blocked;");
    p("    event Blocked(address indexed account, bool state);");
  }
  if (S.tradingToggle) {
    p();
    p("    bool public tradingEnabled;");
    p("    event TradingEnabled();");
  }
  if (S.maxTx) {
    p();
    p("    uint256 public maxTxAmount;");
    p("    uint256 public maxWalletAmount;");
    p("    mapping(address => bool) public limitExempt;");
    p("    event LimitsChanged(uint256 maxTx, uint256 maxWallet);");
  }
  if (S.transferTax) {
    p();
    p("    /// Basis points taken from every transfer. 100 = 1%.");
    p("    uint16 public taxBps;");
    p("    uint16 public constant MAX_TAX_BPS = " + Math.min(10000, Number(S.taxCeilingBps || 1000)) + ";");
    p("    address public taxRecipient;");
    p("    mapping(address => bool) public taxExempt;");
    p("    event TaxChanged(uint16 bps, address recipient);");
  }

  if (S.permit) {
    p();
    p("    // EIP-2612: approve by signature instead of by transaction.");
    p("    mapping(address => uint256) public nonces;");
    if (!up) {
      p("    bytes32 private immutable _CACHED_DOMAIN_SEPARATOR;");
      p("    uint256 private immutable _CACHED_CHAIN_ID;");
    }
    p("    bytes32 private constant _PERMIT_TYPEHASH =");
    p("        keccak256(\"Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)\");");
  }

  /* ---- constructor / initialiser ---- */
  p();
  if (up) {
    p("    /// Runs once, through the proxy, so the supply lands in the proxy's");
    p("    /// storage and not the implementation's. A constructor cannot do that.");
    p("    function initialize() external {");
    p("        require(!_initialized, \"already initialized\");");
    p("        _initialized = true;");
  } else {
    p("    constructor() {");
  }
  if (S.capped && S.mintable) p("        maxSupply = " + String(S.maxSupply) + " * 10 ** " + S.decimals + ";");
  if (S.metaMode && S.metaMode !== "none" && S.metaMutable) {
    const valor = S.metaMode === "inline" ? metadataJSON(S) : String(S.metaUri || "").trim();
    p("        metadataURI = \"" + esc(valor) + "\";");
  }
  p("        totalSupply = " + String(S.supply) + " * 10 ** " + S.decimals + ";");
  p("        balanceOf[msg.sender] = totalSupply;");
  p("        emit Transfer(address(0), msg.sender, totalSupply);");
  if (S.maxTx) {
    p();
    p("        maxTxAmount = " + String(S.maxTxAmount) + " * 10 ** " + S.decimals + ";");
    p("        maxWalletAmount = " + String(S.maxWalletAmount) + " * 10 ** " + S.decimals + ";");
    p("        // The deployer is exempt so the initial liquidity add is not blocked");
    p("        // by the very limits meant for traders. Without this, adding");
    p("        // liquidity reverts and the token looks broken on day one.");
    p("        limitExempt[msg.sender] = true;");
  }
  if (S.transferTax) {
    p();
    p("        taxBps = " + Number(S.taxBps || 0) + ";");
    p("        taxRecipient = msg.sender;");
    p("        taxExempt[msg.sender] = true;");
  }
  if (S.permit && !up) {
    p();
    p("        _CACHED_CHAIN_ID = block.chainid;");
    p("        _CACHED_DOMAIN_SEPARATOR = _buildDomainSeparator();");
  }
  if (owned) {
    p();
    if (S.ownership === "renounce") {
      p("        // Ownership is dropped right here, so no owner-only function above");
      p("        // was ever callable by anyone.");
      p("        emit OwnershipTransferred(address(0), address(0));");
    } else {
      p("        owner = msg.sender;");
      p("        emit OwnershipTransferred(address(0), msg.sender);");
    }
  }
  p("    }");

  /* ---- core transfer logic ---- */
  p();
  p("    function transfer(address to, uint256 value) external returns (bool) {");
  p("        _transfer(msg.sender, to, value);");
  p("        return true;");
  p("    }");
  p();
  p("    function transferFrom(address from, address to, uint256 value) external returns (bool) {");
  p("        uint256 allowed = allowance[from][msg.sender];");
  p("        if (allowed != type(uint256).max) {");
  p("            require(allowed >= value, \"insufficient allowance\");");
  p("            unchecked { allowance[from][msg.sender] = allowed - value; }");
  p("        }");
  p("        _transfer(from, to, value);");
  p("        return true;");
  p("    }");
  p();
  p("    function approve(address spender, uint256 value) external returns (bool) {");
  p("        allowance[msg.sender][spender] = value;");
  p("        emit Approval(msg.sender, spender, value);");
  p("        return true;");
  p("    }");

  p();
  p("    function _transfer(address from, address to, uint256 value) internal {");
  p("        require(to != address(0), \"transfer to the zero address\");");
  if (S.pausable) p("        require(!paused, \"transfers are paused\");");
  if (S.blacklist) {
    p("        require(!blocked[from], \"sender is blocked\");");
    p("        require(!blocked[to], \"recipient is blocked\");");
  }
  if (S.tradingToggle) {
    p("        if (!tradingEnabled) {");
    p("            require(from == owner || to == owner, \"trading is not enabled yet\");");
    p("        }");
  }
  if (S.maxTx) {
    p("        if (!limitExempt[from] && !limitExempt[to]) {");
    p("            require(value <= maxTxAmount, \"over the max transaction limit\");");
    p("            require(balanceOf[to] + value <= maxWalletAmount, \"over the max wallet limit\");");
    p("        }");
  }
  p("        uint256 bal = balanceOf[from];");
  p("        require(bal >= value, \"insufficient balance\");");
  p("        unchecked { balanceOf[from] = bal - value; }");
  if (S.transferTax) {
    p();
    p("        uint256 fee = 0;");
    p("        if (taxBps > 0 && !taxExempt[from] && !taxExempt[to]) {");
    p("            fee = (value * taxBps) / 10000;");
    p("        }");
    p("        if (fee > 0) {");
    p("            balanceOf[taxRecipient] += fee;");
    p("            emit Transfer(from, taxRecipient, fee);");
    p("        }");
    p("        uint256 net = value - fee;");
    p("        balanceOf[to] += net;");
    p("        emit Transfer(from, to, net);");
  } else {
    p("        balanceOf[to] += value;");
    p("        emit Transfer(from, to, value);");
  }
  p("    }");

  /* ---- optional features ---- */
  if (S.burnable) {
    p();
    p("    /// Destroy tokens you hold. Nobody can burn anyone else's balance.");
    p("    function burn(uint256 value) external {");
    p("        uint256 bal = balanceOf[msg.sender];");
    p("        require(bal >= value, \"insufficient balance\");");
    p("        unchecked { balanceOf[msg.sender] = bal - value; }");
    p("        totalSupply -= value;");
    p("        emit Transfer(msg.sender, address(0), value);");
    p("    }");
  }
  if (S.mintable) {
    p();
    p("    function mint(address to, uint256 value) external onlyOwner {");
    if (S.capped) p("        require(totalSupply + value <= maxSupply, \"over the hard cap\");");
    p("        totalSupply += value;");
    p("        balanceOf[to] += value;");
    p("        emit Transfer(address(0), to, value);");
    p("    }");
  }
  if (S.pausable) {
    p();
    p("    function setPaused(bool state) external onlyOwner {");
    p("        paused = state;");
    p("        emit Paused(state);");
    p("    }");
  }
  if (S.blacklist) {
    p();
    p("    function setBlocked(address account, bool state) external onlyOwner {");
    p("        blocked[account] = state;");
    p("        emit Blocked(account, state);");
    p("    }");
  }
  if (S.tradingToggle) {
    p();
    p("    /// One-way. Once trading is on it can never be turned off again.");
    p("    function enableTrading() external onlyOwner {");
    p("        require(!tradingEnabled, \"already enabled\");");
    p("        tradingEnabled = true;");
    p("        emit TradingEnabled();");
    p("    }");
  }
  if (S.maxTx) {
    p();
    p("    function setLimits(uint256 newMaxTx, uint256 newMaxWallet) external onlyOwner {");
    p("        maxTxAmount = newMaxTx;");
    p("        maxWalletAmount = newMaxWallet;");
    p("        emit LimitsChanged(newMaxTx, newMaxWallet);");
    p("    }");
    p();
    p("    function setLimitExempt(address account, bool state) external onlyOwner {");
    p("        limitExempt[account] = state;");
    p("    }");
  }
  if (S.transferTax) {
    p();
    p("    function setTax(uint16 bps, address recipient) external onlyOwner {");
    p("        require(bps <= MAX_TAX_BPS, \"over the hard tax ceiling\");");
    p("        require(recipient != address(0), \"zero recipient\");");
    p("        taxBps = bps;");
    p("        taxRecipient = recipient;");
    p("        emit TaxChanged(bps, recipient);");
    p("    }");
    p();
    p("    function setTaxExempt(address account, bool state) external onlyOwner {");
    p("        taxExempt[account] = state;");
    p("    }");
  }

  if (S.metaMode && S.metaMode !== "none" && S.metaMutable) {
    p();
    p("    /// Lets you fix a broken link later. It also lets you swap the picture");
    p("    /// and the description for something else entirely, at any time.");
    p("    function setMetadataURI(string calldata uri) external onlyOwner {");
    p("        metadataURI = uri;");
    p("    }");
  }

  if (S.permit) {
    p();
    if (up) {
      p("    /// Rebuilt on every call rather than cached. A cached separator would");
      p("    /// be computed with the implementation's address, not the proxy's, and");
      p("    /// every signature would fail to verify.");
      p("    function DOMAIN_SEPARATOR() public view returns (bytes32) {");
      p("        return _buildDomainSeparator();");
      p("    }");
    } else {
      p("    function DOMAIN_SEPARATOR() public view returns (bytes32) {");
      p("        return block.chainid == _CACHED_CHAIN_ID");
      p("            ? _CACHED_DOMAIN_SEPARATOR");
      p("            : _buildDomainSeparator();");
      p("    }");
    }
    p();
    p("    function _buildDomainSeparator() private view returns (bytes32) {");
    p("        return keccak256(abi.encode(");
    p("            keccak256(\"EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)\"),");
    p("            keccak256(bytes(name)),");
    p("            keccak256(bytes(\"1\")),");
    p("            block.chainid,");
    p("            address(this)");
    p("        ));");
    p("    }");
    p();
    p("    function permit(");
    p("        address tokenOwner, address spender, uint256 value,");
    p("        uint256 deadline, uint8 v, bytes32 r, bytes32 s");
    p("    ) external {");
    p("        require(block.timestamp <= deadline, \"permit expired\");");
    p("        bytes32 structHash = keccak256(abi.encode(");
    p("            _PERMIT_TYPEHASH, tokenOwner, spender, value, nonces[tokenOwner]++, deadline");
    p("        ));");
    p("        bytes32 digest = keccak256(abi.encodePacked(\"\\x19\\x01\", DOMAIN_SEPARATOR(), structHash));");
    p("        address recovered = ecrecover(digest, v, r, s);");
    p("        require(recovered != address(0) && recovered == tokenOwner, \"bad signature\");");
    p("        allowance[tokenOwner][spender] = value;");
    p("        emit Approval(tokenOwner, spender, value);");
    p("    }");
  }

  if (owned && S.ownership !== "renounce") {
    p();
    p("    function transferOwnership(address newOwner) external onlyOwner {");
    p("        emit OwnershipTransferred(owner, newOwner);");
    p("        owner = newOwner;");
    p("    }");
    p();
    p("    /// Permanent. Every onlyOwner function above becomes uncallable forever.");
    p("    function renounceOwnership() external onlyOwner {");
    p("        emit OwnershipTransferred(owner, address(0));");
    p("        owner = address(0);");
    p("    }");
  }

  p("}");

  if (up) L.push("", ...proxyLines());
  return L.join("\n") + "\n";
}

/* The proxy. Standard ERC-1967 slots so explorers and wallets recognise it.
 * Kept short enough to read in one sitting, because the whole risk of this
 * pattern is in six lines of it. */
function proxyLines() {
  return [
    "/*",
    " * The proxy holds the storage; the implementation holds the code. Calls",
    " * land here and are delegated onward, so the token's address never changes",
    " * even when its behaviour does.",
    " *",
    " * WHAT THE ADMIN CAN DO, stated plainly: upgradeTo() points this at any",
    " * other contract. That new contract inherits every balance, and can do",
    " * anything with them — mint, freeze, blacklist, or refuse to transfer at",
    " * all. No audit of the implementation can rule that out, because the",
    " * implementation is the part that gets replaced.",
    " *",
    " * upgradeTo, changeAdmin, admin and implementation live on the proxy and",
    " * are NOT forwarded. If a future implementation defines a function with",
    " * one of those four selectors, it will be unreachable through this proxy.",
    " */",
    "contract TokenProxy {",
    "    // keccak256('eip1967.proxy.implementation') - 1",
    "    bytes32 private constant _IMPL_SLOT = 0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc;",
    "    // keccak256('eip1967.proxy.admin') - 1",
    "    bytes32 private constant _ADMIN_SLOT = 0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103;",
    "",
    "    event Upgraded(address indexed implementation);",
    "    event AdminChanged(address previousAdmin, address newAdmin);",
    "",
    "    constructor(address implementation_, address admin_, bytes memory data) {",
    "        _setSlot(_IMPL_SLOT, implementation_);",
    "        _setSlot(_ADMIN_SLOT, admin_);",
    "        emit Upgraded(implementation_);",
    "        emit AdminChanged(address(0), admin_);",
    "        if (data.length > 0) {",
    "            (bool ok, bytes memory ret) = implementation_.delegatecall(data);",
    "            require(ok, _reason(ret));",
    "        }",
    "    }",
    "",
    "    function admin() external view returns (address) { return _getSlot(_ADMIN_SLOT); }",
    "",
    "    function implementation() external view returns (address) { return _getSlot(_IMPL_SLOT); }",
    "",
    "    function upgradeTo(address newImplementation) external {",
    "        require(msg.sender == _getSlot(_ADMIN_SLOT), \"not the admin\");",
    "        require(newImplementation.code.length > 0, \"not a contract\");",
    "        _setSlot(_IMPL_SLOT, newImplementation);",
    "        emit Upgraded(newImplementation);",
    "    }",
    "",
    "    /// Setting the admin to the zero address makes this proxy permanent:",
    "    /// no upgrade can ever happen again, and the code becomes as fixed as a",
    "    /// plain deployment. It is the only way to undo this pattern.",
    "    function changeAdmin(address newAdmin) external {",
    "        address cur = _getSlot(_ADMIN_SLOT);",
    "        require(msg.sender == cur, \"not the admin\");",
    "        _setSlot(_ADMIN_SLOT, newAdmin);",
    "        emit AdminChanged(cur, newAdmin);",
    "    }",
    "",
    "    function _getSlot(bytes32 slot) private view returns (address a) {",
    "        assembly { a := sload(slot) }",
    "    }",
    "",
    "    function _setSlot(bytes32 slot, address a) private {",
    "        assembly { sstore(slot, a) }",
    "    }",
    "",
    "    function _reason(bytes memory ret) private pure returns (string memory) {",
    "        if (ret.length < 68) return \"initialize failed\";",
    "        assembly { ret := add(ret, 0x04) }",
    "        return abi.decode(ret, (string));",
    "    }",
    "",
    "    fallback() external payable {",
    "        address impl = _getSlot(_IMPL_SLOT);",
    "        assembly {",
    "            calldatacopy(0, 0, calldatasize())",
    "            let ok := delegatecall(gas(), impl, 0, calldatasize(), 0, 0)",
    "            returndatacopy(0, 0, returndatasize())",
    "            switch ok",
    "            case 0 { revert(0, returndatasize()) }",
    "            default { return(0, returndatasize()) }",
    "        }",
    "    }",
    "",
    "    receive() external payable {}",
    "}",
  ];
}

/* Plain-language list of what the generated contract can do to a holder.
 * Derived from the same state the source is, so the two cannot drift apart. */
export function powerList(state) {
  const out = [];
  if (state.metaMutable && state.metaMode && state.metaMode !== "none") {
    out.push("change the picture, the description and the links at any time");
  }
  if (state.upgradeable) out.push("replace the entire contract with different code, keeping everyone's balances");
  if (state.mintable) out.push(state.capped ? "create new tokens up to a fixed cap" : "create unlimited new tokens");
  if (state.pausable) out.push("freeze all transfers");
  if (state.blacklist) out.push("block individual addresses");
  if (state.tradingToggle) out.push("decide when (or whether) trading starts");
  if (state.maxTx) out.push("change how much can be moved or held");
  if (state.transferTax) out.push("change the transfer fee");
  return out;
}
